### ISSUE TITLE
Hello i need some help with tensorflow.org/js object recognition

### ISSUE THREAD

**Issue by mtrucc** [ajaichemmanam/object-detection-react-tfjs#17]
I trained the model according to this tutorial, but it doesn't work, seems to be too new
- [Custom object detection in the browser using TensorFlow.js](https://blog.tensorflow.org/2021/01/custom-object-detection-in-browser.html)
- [Training a model for custom object detection (TF 2.x) on Google Colab](https://techzizou.com/training-an-ssd-model-for-a-custom-object-using-tensorflow-2-x/)

After I load the model in this example, I got some errors
https://github.com/tensorflow/tfjs-models/tree/master/coco-ssd

Error：https://github.com/tensorflow/tfjs/issues/4638

I don't understand the reason, but I also don't understand the model output information

**Comment by ajaichemmanam** [comment]
Mostly it might be some compatibility issues with tensorflow and tensorflowjs versions. can't tell much. Please share your model and give more info

**Comment by mtrucc** [comment]
Here is a working sample code

https://github.com/mtrucc/react-ts-fpkqes

Here is the working model

https://github.com/mtrucc/react-ts-fpkqes/tree/main/public/mask_model

This is the model I trained myself and converted using the command, it doesn't work

https://github.com/mtrucc/react-ts-fpkqes/tree/main/public/mask_model2

You can switch models by modifying the path in the code

https://github.com/mtrucc/react-ts-fpkqes/blob/6cb2ce09f4c44673098749041244b0f998f8d8f4/src/components/mask.js#L35

Install tensorflowjs

```
!pip install tensorflowjs
```

Return

```
Successfully installed flatbuffers-1.12 gast-0.4.0 keras-2.9.0 packaging-20.9 protobuf-3.20.0 tensorboard-2.9.0 tensorflow-2.9.0 tensorflow-estimator-2.9.0 tensorflowjs-3.19.0
```

Here is my conversion command in colab

```
tensorflowjs_converter --input_format=tf_saved_model \
                        --output_format=tfjs_graph_model \
  /content/gdrive/MyDrive/customTF2/data/inference_graph/saved_model \
  /content/gdrive/MyDrive/customTF2/data/inference_graph/saved_model_js
I don't know where is the problem? If you need more details, I can add.
```

I don't know where is the problem? If you need more details, I can add.

**Comment by mtrucc** [comment]
Hi I would like to know how did you train and convert the model @ajaichemmanam

**Comment by mtrucc** [comment]
The issue has been resolved, it was the format of the model output that was different

**Comment by mayukhdeep12** [comment]
Hello, @mtrucc I'm having the same problem, if you could tell me how you fixed it and what the proper format, that would be very helpful.
